operational ROOT macro example
need to explicitly run executable through a bash terminal for some
reason, idk why

without this change, I'd get an error like the following which I have no
idea how to resolve since I can't replicate this locally

ERROR: Unable to find unpacked image 'condor_exec.exe' under
/cvmfs/unpacked.cern.ch/registry.hub.docker.com path(s).